### ISSUE TITLE
Missing MPD-Composite Code and Question About MPDComposite Class

### ISSUE THREAD

**Issue by jh-source** [yoraish/mmd#2]
Hi, thank you for sharing this great work and for making the repository available! I found it very interesting that your approach outperformed MPD, as mentioned in the paper:

> "We evaluated MPD-Composite, a state-of-the-art motion planning diffusion model (MPD) that we trained on multi-robot data we collected in two maps."

I was looking through the repository but could not find the code for training and inference of the MPD baseline. The original MPD only can be used for single robot motion planning so I was wondering if it would be possible to open source this part? Also, I noticed that the README mentions an MPDComposite class, but I could not find this class in the code.

It would be great if you could provide some clarification or guidance on these. Thanks so much for your help!

**Comment by yoraish** [comment]
Thanks for your interest in our work! Please consult the (newly updated) `mpd-composite` branch for all the relevant code you mentioned.
